import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoryBlokProvider from "@/components/StoryBlokProvider";
import { getStoryblokApi } from "@/lib/storyblok";
import Header from "@/components/sb/Header";
import Footer from "@/components/sb/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const storyblok = getStoryblokApi();
  const global = await storyblok.get("cdn/stories/global", {
    version: "draft",
  });

  return (
    <StoryBlokProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header blok={global.data.story.content.header[0]} />
          {children}
          <Footer blok={global.data.story.content.footer[0]} />
        </body>
      </html>
    </StoryBlokProvider>
  );
}
